### ISSUE TITLE
Mix of address families

### ISSUE THREAD

**Issue by nokia1adam** [jhaas-pfrc/draft-ietf-idr-flowspec-redirect-ip#10]
Should we add some text to describe how an implementation should be prepared to receive an IPv4 target address in an IPv6 flowspec route, or inversely, an IPv6 target address in an IPv4 flowspec route?

Do implementations support that? (I will double-check but I think Nokia may require the target address to be same family as the NLRI.)

**Comment by jhaas-pfrc** [comment]
I think Juniper's behavior requires matching encapsulation as well.  I'll check into it.

**Comment by jhaas-pfrc** [comment]
I’ve added some text in the branch for -03 that tries to address this point.
```
+       <t>Traffic that is to be redirected/copied for a "redirect-to-IP"
+       extended community SHOULD only be redirected if the community type
+       matches the traffic type.</t>
```
