### ISSUE TITLE
Validation procedure recommends discarding non-validating redirect-to-ip extended communities

### ISSUE THREAD

**Issue by jhaas-pfrc** [jhaas-pfrc/draft-ietf-idr-flowspec-redirect-ip#7]
Adam's suggested text recommends that when origin validation fails (for the offered new procedure), the redirect-to-ip extended community should be discarded.

However, given that it may later be validated due to a change in routing state, discarding is almost certainly the wrong thing to do.

If we keep the validation procedures, we'll likely want to adjust this text to cover ignoring rather than discarding.  This needs discussion.

If we don't keep the additional validation procedures, this issue can be closed with no action.

**Comment by nokia1adam** [comment]
I didn't realize I made this suggestion. I agree that discarding seems wrong. Ignoring seems more appropriate.

For what it is worth, I think the validation is OK to keep if we agree it offers some protection, in some cases, and it is configurable (can be disabled if needed).

**Comment by jhaas-pfrc** [comment]
I’ve updated the text to recommend that we SHOULD ignore things.

```
   If any of the above checks determine that a "redirect-to-IP" extended
   community is invalid, the extended community SHOULD be ignored.
```
